name: memory_cards
description: Offline-first photo memory cards MVP.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.9.0
  file_selector: ^1.1.0
  just_audio: ^0.10.6
  just_audio_media_kit: ^2.1.0
  media_kit_libs_windows_audio: ^1.0.9
  record: ^7.1.1
  path: ^1.9.0
  path_provider: ^2.1.5
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true



